sudo: required
dist: trusty
language: node_js

node_js:
- '6.9.1'
- 'stable'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - google-chrome
    packages:
    - google-chrome-stable
    - g++-4.8

cache:
  directories:
  - node_modules

env:
  matrix:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-release
  global:
    - CXX=g++-4.8
    - secure: PzWXGNPWdY4n9Xj9rvFFB67wn6u/ZkKjghXZ0qctWI58qaI5UmqCzDNUVguRrU4i9L5zjuEGUS8jkhMS/z3WLubiCyLQlhBLtS72YK5GPzm2fogzvtyXhN0a71AliruKeUZqz+I421FZUfWpuoY0LWGb4VHYYZ2kiUtQo6P4hrhjQXbXbidbvlFFkqhrHt/fYUSOtynSJgm0BVLH7/YzLohWCtefmkRe0P1SsRQ/IhvcT1kqdCwBUyoghrr/IDA7CosnoWgEEGL9UztY43pVwYWmG2dVFYsGN5/NhZF6CoAHV0RPRbzetzp2Xs1nHkIfHdjCYC+9J8ruNZgBv0cp6nbF7qrbkODI91UHSMhqbixfNik7YDST1eJqzozWR4nQD8/UKvZt3AAe3ZO3qLRkSdaJQOxgrRAfdHZR70C04AevzqCrfCZI4SpOvTKq7sGUmKuCTB8aRr8C/fsVJRoUqS9mStjgcD1x7zEXGgtd6q3o+D1Mln/uNIVbAQ7PxpCdSXrQ/xS8X07FhoirFkGTYnj9lLIpAxKMsjxj8lFCtmLi8YB8G+Gfp/XXn9NfhBVzlK8bgM+T/KFVir0CYng60104QAtlHFTEIZjRM95GkP5yYA6nLtSyI0UJi6ZCRtefT6quYMH+CsvZyU2jOc32LNclO8pJwwMV1rcEjCoA3hw=

matrix:
  fast_finish: true
  allow_failures:
  - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
- npm config set spin false
- npm install -g coveralls pr-bumper@^1.0.0
- $(npm root -g)/pr-bumper/.travis/maybe-check-scope.sh

install:
- $(npm root -g)/pr-bumper/.travis/maybe-install.sh

before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start

script:
- $(npm root -g)/pr-bumper/.travis/maybe-test.sh
- $(npm root -g)/pr-bumper/.travis/maybe-test.sh coverage
- .travis/maybe-bump-version.sh

after_success:
- .travis/maybe-publish-coverage.sh
- .travis/maybe-publish-gh-pages.sh

deploy:
  provider: npm
  email: npm.ciena@gmail.com
  skip_cleanup: true
  api_key:
    secure: N3h/UssNhFlzUJenh3LqtiaRUlJuqa8Y+yBIRsaT+WaoB6INOGrS/Zgq5HoPrCF0Wm3jj8XvmatcbImltY9hHomiBuHrUNiysn0+d3GzVfhEuyyPwbif+FC28XtfFXzNPubBAfkDI4QsXgn5IPbbGVBIflGC0YTMSv9NfyCLtDlkeQavL1sl6xMsvE2G8XzVs89SHwyuH4L9FFIAjkp1MENL3nr6B/1fZFF6HB0Oq1KGxOXikuyiTc68WeP88Qpgb56OOnMrAqqciR4uDELLSjSTuXoHKwhsWB1/QVAp41G7oizisuc9kpuG/YHDXlV0DgDIakIl9/MvC2s6Ls9wTe6h04opMtOmV5f/3fb2Rhv+aRkKbhI5Bt4ygTNnZ/ZznR0f/51GnNn9Vmt9e7BAOSFwuTUjuroKoSsPC3SIZuu5wfWQvwJB2miQALFr2as7B2j7or9v9JD4gkNB901+WMYMF+c2z4ON9HEG6xH2nXK87gmmKWSS9DYIhPRv5pm1Gae6tMfZteF0Jszrf8U2J4zSKCuRqz11Oq/QNnKndLmBaNkEf0ptb/28gDTkyUNhVyLpI427DbGoje0NOTJ2aK7SpsMsNKwml9G98NbjpJN6AOmV7vjfGXgd/SOv7EM+YmYpvND7/Zb5+D0efbkPAW2ZR8YmKsyJuM31WJ2wGZY=
  on:
    all_branches: true
    condition: "$EMBER_TRY_SCENARIO = 'default'"
    node: '6.9.1'
    tags: true

notifications:
  slack:
    secure: ZNQs1LgIyI6ZiMgqMClV98bA081ph4iDerdDIFsU9lbzLy5SM2mND+DswefhCh4WWPgDzEIfM0F7EmcIVQdY6aNVgEFrbkx9g3Xb5nElf0ufF1kr/nFW7V5Yib7l/PeuuMY8ZyD3FD/qmwtsYaT+ism5X4Yv5GesnNn6JHWWR9YuegoCyZkBQkHG/1m5db9ldI+fwruSQEbrD1ofNdAp1nuF7sQOvb0YZ1Yv7eZs0Q/+J1Nh4S1CnqR/G5y/+bfRFMzkMqztOXuj+CYzRphz9TDy+TEcHIHyCmNKYtr4vJIhyaVS+SkH8hlbM0mNJCVg3MBYJ1D8uGO2m+MdUF1dHGQ0tRdXFhUMS7Rgk4o07/qoVw34OyWQ1roGKR2TShWXnUeqPpqe9EADkDWng3aFtud6Jmdg9u9NQ2g/6izL1riRzua68btwWssb6CxdgOFL8EJa4ngvblV4YpfMUpKTt6H9vHtmMZDGuNtmv3TcoiTIKUOH3DVOl8y4GVRMTbT90XjL+OIPLXj7hJcKJOxV/72A3Fy++3XS9l2rNM6P8n7AJ52zwrvBY6tWtHVxnruCzjcR3nswtexkVXkdcpuxVCncxFGxp4Lr1IrJudBxVSeiIJ7a9VfA6hZujzxF8OcIyTJS1B/iW1mbA2+nHzS1CVS3EmnsCGMVFI1hQLn7KSY=
